# Generated by Django 5.0.1 on 2024-02-01 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=255)),
                ('Name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('size', models.IntegerField()),
                ('measure_unit', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('color', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=10)),
            ],
        ),
    ]
